package paunch

import (
	glfw "github.com/go-gl/glfw3"
)

const tolerance = 0.01

// Constants for directions
const (
	_ = iota
	Up
	Down
	Left
	Right
)

// Constants for action types.
const (
	Press   = int(glfw.Press)
	Release = int(glfw.Release)
	Hold    = int(glfw.Repeat)
)

// Constants defining mouse button values.
const (
	MouseButton1      = int(glfw.MouseButton1)
	MouseButton2      = int(glfw.MouseButton2)
	MouseButton3      = int(glfw.MouseButton3)
	MouseButton4      = int(glfw.MouseButton4)
	MouseButton5      = int(glfw.MouseButton5)
	MouseButton6      = int(glfw.MouseButton6)
	MouseButton7      = int(glfw.MouseButton7)
	MouseButton8      = int(glfw.MouseButton8)
	MouseButtonLast   = int(glfw.MouseButtonLast)
	MouseButtonLeft   = int(glfw.MouseButtonLeft)
	MouseButtonRight  = int(glfw.MouseButtonRight)
	MouseButtonMiddle = int(glfw.MouseButtonMiddle)
)

// Constants defining key values.
const (
	KeyUnknown      = int(glfw.KeyUnknown)
	KeySpace        = int(glfw.KeySpace)
	KeyApostrophe   = int(glfw.KeyApostrophe)
	KeyComma        = int(glfw.KeyComma)
	KeyMinus        = int(glfw.KeyMinus)
	KeyPeriod       = int(glfw.KeyPeriod)
	KeySlash        = int(glfw.KeySlash)
	Key0            = int(glfw.Key0)
	Key1            = int(glfw.Key1)
	Key2            = int(glfw.Key2)
	Key3            = int(glfw.Key3)
	Key4            = int(glfw.Key4)
	Key5            = int(glfw.Key5)
	Key6            = int(glfw.Key6)
	Key7            = int(glfw.Key7)
	Key8            = int(glfw.Key8)
	Key9            = int(glfw.Key9)
	KeySemicolon    = int(glfw.KeySemicolon)
	KeyEqual        = int(glfw.KeyEqual)
	KeyA            = int(glfw.KeyA)
	KeyB            = int(glfw.KeyB)
	KeyC            = int(glfw.KeyC)
	KeyD            = int(glfw.KeyD)
	KeyE            = int(glfw.KeyE)
	KeyF            = int(glfw.KeyF)
	KeyG            = int(glfw.KeyG)
	KeyH            = int(glfw.KeyH)
	KeyI            = int(glfw.KeyI)
	KeyJ            = int(glfw.KeyJ)
	KeyK            = int(glfw.KeyK)
	KeyL            = int(glfw.KeyL)
	KeyM            = int(glfw.KeyM)
	KeyN            = int(glfw.KeyN)
	KeyO            = int(glfw.KeyO)
	KeyP            = int(glfw.KeyP)
	KeyQ            = int(glfw.KeyQ)
	KeyR            = int(glfw.KeyR)
	KeyS            = int(glfw.KeyS)
	KeyT            = int(glfw.KeyT)
	KeyU            = int(glfw.KeyU)
	KeyV            = int(glfw.KeyV)
	KeyW            = int(glfw.KeyW)
	KeyX            = int(glfw.KeyX)
	KeyY            = int(glfw.KeyY)
	KeyZ            = int(glfw.KeyZ)
	KeyLeftBracket  = int(glfw.KeyLeftBracket)
	KeyBackslash    = int(glfw.KeyBackslash)
	KeyRightBracket = int(glfw.KeyRightBracket)
	KeyGraveAccent  = int(glfw.KeyGraveAccent)
	KeyWorld1       = int(glfw.KeyWorld1)
	KeyWorld2       = int(glfw.KeyWorld2)
	KeyEscape       = int(glfw.KeyEscape)
	KeyEnter        = int(glfw.KeyEnter)
	KeyTab          = int(glfw.KeyTab)
	KeyBackspace    = int(glfw.KeyBackspace)
	KeyInsert       = int(glfw.KeyInsert)
	KeyDelete       = int(glfw.KeyDelete)
	KeyRight        = int(glfw.KeyRight)
	KeyLeft         = int(glfw.KeyLeft)
	KeyDown         = int(glfw.KeyDown)
	KeyUp           = int(glfw.KeyUp)
	KeyPageUp       = int(glfw.KeyPageUp)
	KeyPageDown     = int(glfw.KeyPageDown)
	KeyHome         = int(glfw.KeyHome)
	KeyEnd          = int(glfw.KeyEnd)
	KeyCapsLock     = int(glfw.KeyCapsLock)
	KeyScrollLock   = int(glfw.KeyScrollLock)
	KeyNumLock      = int(glfw.KeyNumLock)
	KeyPrintScreen  = int(glfw.KeyPrintScreen)
	KeyPause        = int(glfw.KeyPause)
	KeyF1           = int(glfw.KeyF1)
	KeyF2           = int(glfw.KeyF2)
	KeyF3           = int(glfw.KeyF3)
	KeyF4           = int(glfw.KeyF4)
	KeyF5           = int(glfw.KeyF5)
	KeyF6           = int(glfw.KeyF6)
	KeyF7           = int(glfw.KeyF7)
	KeyF8           = int(glfw.KeyF8)
	KeyF9           = int(glfw.KeyF9)
	KeyF10          = int(glfw.KeyF10)
	KeyF11          = int(glfw.KeyF11)
	KeyF12          = int(glfw.KeyF12)
	KeyF13          = int(glfw.KeyF13)
	KeyF14          = int(glfw.KeyF14)
	KeyF15          = int(glfw.KeyF15)
	KeyF16          = int(glfw.KeyF16)
	KeyF17          = int(glfw.KeyF17)
	KeyF18          = int(glfw.KeyF18)
	KeyF19          = int(glfw.KeyF19)
	KeyF20          = int(glfw.KeyF20)
	KeyF21          = int(glfw.KeyF21)
	KeyF22          = int(glfw.KeyF22)
	KeyF23          = int(glfw.KeyF23)
	KeyF24          = int(glfw.KeyF24)
	KeyF25          = int(glfw.KeyF25)
	KeyKp0          = int(glfw.KeyKp0)
	KeyKp1          = int(glfw.KeyKp1)
	KeyKp2          = int(glfw.KeyKp2)
	KeyKp3          = int(glfw.KeyKp3)
	KeyKp4          = int(glfw.KeyKp4)
	KeyKp5          = int(glfw.KeyKp5)
	KeyKp6          = int(glfw.KeyKp6)
	KeyKp7          = int(glfw.KeyKp7)
	KeyKp8          = int(glfw.KeyKp8)
	KeyKp9          = int(glfw.KeyKp9)
	KeyKpDecimal    = int(glfw.KeyKpDecimal)
	KeyKpDivide     = int(glfw.KeyKpDivide)
	KeyKpMultiply   = int(glfw.KeyKpMultiply)
	KeyKpSubtract   = int(glfw.KeyKpSubtract)
	KeyKpAdd        = int(glfw.KeyKpAdd)
	KeyKpEnter      = int(glfw.KeyKpEnter)
	KeyKpEqual      = int(glfw.KeyKpEqual)
	KeyLeftShift    = int(glfw.KeyLeftShift)
	KeyLeftControl  = int(glfw.KeyLeftControl)
	KeyLeftAlt      = int(glfw.KeyLeftAlt)
	KeyLeftSuper    = int(glfw.KeyLeftSuper)
	KeyRightShift   = int(glfw.KeyRightShift)
	KeyRightControl = int(glfw.KeyRightControl)
	KeyRightAlt     = int(glfw.KeyRightAlt)
	KeyRightSuper   = int(glfw.KeyRightSuper)
	KeyMenu         = int(glfw.KeyMenu)
	KeyLast         = int(glfw.KeyLast)
)
